spring:
  application:
    name: consult
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:consultDB;IFEXISTS=FALSE;
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
